// Shared TypeScript types for MedSpace
// ─── Display Labels ──────────────────────────────────────────────────────────
export const SPACE_TYPE_LABELS = {
    EXAM_ROOM: 'Exam Room',
    SURGICAL_SUITE: 'Surgical Suite',
    IMAGING_CENTER: 'Imaging Center',
    DENTAL_OFFICE: 'Dental Office',
    THERAPY_ROOM: 'Therapy Room',
    LAB: 'Laboratory',
    FULL_OFFICE: 'Full Medical Office',
    MEDICAL_SPA: 'Medical Spa',
    URGENT_CARE: 'Urgent Care',
    OTHER: 'Other',
};
export const LISTING_TYPE_LABELS = {
    LEASE: 'For Lease',
    SUBLET: 'Sublet',
    SHARED: 'Shared Space',
    HOURLY: 'Hourly',
};
// ─── Common Amenities ────────────────────────────────────────────────────────
export const AMENITIES_LIST = [
    'HIPAA Compliant',
    'Electronic Health Records',
    'X-Ray Equipment',
    'Lab Services',
    'Waiting Room',
    'Reception Desk',
    'Private Parking',
    'ADA Accessible',
    'High-Speed WiFi',
    'Video Conferencing',
    'Break Room',
    'Storage Space',
    'Medical Waste Disposal',
    'Security System',
    'Air Filtration System',
    'Exam Tables Included',
    'Sterilization Equipment',
    '24/7 Access',
    'Cleaning Services',
    'Billing Support',
];
// ─── Medical Specialties ─────────────────────────────────────────────────────
export const MEDICAL_SPECIALTIES = [
    'All Specialties',
    'Internal Medicine',
    'Family Medicine',
    'Cardiology',
    'Dermatology',
    'Endocrinology',
    'Gastroenterology',
    'Neurology',
    'Oncology',
    'Orthopedics',
    'Pediatrics',
    'Psychiatry',
    'Pulmonology',
    'Radiology',
    'Rheumatology',
    'Urology',
    'OB/GYN',
    'Ophthalmology',
    'ENT',
    'Physical Therapy',
    'Occupational Therapy',
    'Dentistry',
    'Orthodontics',
    'Chiropractic',
    'Aesthetics',
    'Urgent Care',
];
